// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmqhyvEea78zgXqhnoh-kGMvAW8R9v4Z4',
    appId: '1:854045667991:web:b5e34578a5d64fbeccafd2',
    messagingSenderId: '854045667991',
    projectId: 'cervezapp-258b2',
    authDomain: 'cervezapp-258b2.firebaseapp.com',
    storageBucket: 'cervezapp-258b2.firebasestorage.app',
    measurementId: 'G-YVLZCE1W7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPTMintUWmbISyD8OFdAf6-_BMGXL91Y0',
    appId: '1:854045667991:android:7421d33caf1e5935ccafd2',
    messagingSenderId: '854045667991',
    projectId: 'cervezapp-258b2',
    storageBucket: 'cervezapp-258b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOObrmH4P2-F0O1-_tLHiTEpdHxCm8aMY',
    appId: '1:854045667991:ios:b02854864265aba1ccafd2',
    messagingSenderId: '854045667991',
    projectId: 'cervezapp-258b2',
    storageBucket: 'cervezapp-258b2.firebasestorage.app',
    iosBundleId: 'com.example.cervezapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmqhyvEea78zgXqhnoh-kGMvAW8R9v4Z4',
    appId: '1:854045667991:web:55dddc945ecb1d46ccafd2',
    messagingSenderId: '854045667991',
    projectId: 'cervezapp-258b2',
    authDomain: 'cervezapp-258b2.firebaseapp.com',
    storageBucket: 'cervezapp-258b2.firebasestorage.app',
    measurementId: 'G-7KD15W1LLW',
  );
}
